services:
  - type: web
    name: product-listing-api
    runtime: python3
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: python -m uvicorn main:app --host 0.0.0.0 --port $PORT
    plan: free
    env: python
    healthCheckPath: /
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.6
      - key: RENDER
        value: true